name: Slack Notifications

on:
  workflow_run:
    workflows: ['Test CI']                     
    types:
      - completed

jobs:
  notifySlack:

    runs-on: ubuntu-latest

    steps:
    - name: Create Test Report
      id: testReport
      uses: dorny/test-reporter@v1
      with:
        artifact: test-results            # artifact name
        name: xUnit Tests                  # Name of the check run which will be created
        path: '*.trx'                     # Path to test results (inside artifact .zip)
        reporter: dotnet-trx
        only-summary: 'false'
        list-suites: 'all'
        list-tests: 'all'
        max-annotations: '10'
        working-directory: ''
        
    - uses: 5monkeys/cobertura-action@master
      with:
          path: coverage.cobertura.xml
          minimum_coverage: 75
