name: Slack Notifications

on:
  workflow_run:
    workflows: ['Test CI']                     
    types:
      - completed

jobs:
  notifySlack:

    runs-on: ubuntu-latest

    steps:
    - name: Create Test Report
      id: testReport
      uses: dorny/test-reporter@v1
      with:
        artifact: test-results            # artifact name
        name: xUnit Tests                  # Name of the check run which will be created
        path: '*.trx'                     # Path to test results (inside artifact .zip)
        reporter: dotnet-trx
        only-summary: 'false'
        list-suites: 'all'
        list-tests: 'all'
        max-annotations: '10'
        working-directory: ''
        
    - name: Notify slack
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: abinoda/slack-action@master
      with:
        args: '{\"channel\":\"C03V5CCT72T\",\"blocks\": [{\"type\":\"header\",\"text\": {\"type\":\"plain_text\",\"text\":\"Commit Information\",\"emoji\": true}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Repository:* ${{ github.event.repository.name }}\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Commit Message:* ${{ github.event.workflow_run.head_commit.message }}\"}},{\"type\":\"section\",\"text\": {\"type\":\"mrkdwn\",\"text\":\"*Author:* ${{ github.event.workflow_run.head_commit.author.name }}\"}},{\"type\":\"section\",\"text\": {\"type\":\"mrkdwn\",\"text\":\"*Build Status:* ![]( ${{ github.event.workflow.badge_url }} )\"}},{\"type\": \"divider\"},{\"type\":\"header\",\"text\": {\"type\": \"plain_text\",\"text\": \"Tests Information\"}},{\"type\": \"section\",\"text\": {\"type\": \"mrkdwn\",\"text\":\" test\"	}}]}'
